name: Validate Gradle Wrapper workflow

on: [workflow_call]

jobs:
  validate:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v3
